import type { Metadata, Viewport } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect } from "next/navigation";
import SessionProvider from "@/components/SessionProvider";

export const metadata: Metadata = {
    title: "Admin Panel - KeepPlay Engine",
    description: "Secure administrative interface for KeepPlay Engine",
    robots: "noindex, nofollow",
    // Use the public PWA host for manifest/icons to keep install public
    manifest: "https://public-pwa.vercel.app/admin-manifest.json?v=20260316-3",
    appleWebApp: {
        capable: true,
        statusBarStyle: "default",
        title: "KPE Admin",
    },
    formatDetection: {
        telephone: false,
    },
    icons: {
        // Browsers often keep using /favicon.ico for the tab unless we provide a
        // small, route-specific icon. These endpoints are generated by
        // src/app/admin/icon.tsx and src/app/admin/apple-icon.tsx.
        icon: "/admin/icon?v=20260316-2",
        shortcut: "/admin/icon?v=20260316-2",
        apple: "/admin/apple-icon?v=20260316-2",
    },
};

export const viewport: Viewport = {
    themeColor: "#2563eb",
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
};

export default async function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);

    // Server-side authentication + role check (defense-in-depth — H01)
    // Cloudflare Access + proxy.ts provide outer layers, this is the final guard
    const userRole = session?.user?.role;
    const isAuthorizedRole = userRole === "SUPER_ADMIN" || userRole === "ADMIN" || userRole === "MODERATOR";

    // Only enforce role check for non-login pages.
    // Login page must remain accessible to unauthenticated users.
    // We detect login by checking if session is absent (unauthenticated → going to login).
    if (session && !isAuthorizedRole) {
        redirect("/admin/login");
    }

    return (
        <SessionProvider session={session}>
            {children}
        </SessionProvider>
    );
}
